### ISSUE TITLE
Could not read `.cargo/git/checkouts/substrate-7e08433d4c370a21/57346f6/primitives/trie/Cargo.toml

### ISSUE THREAD

**Issue by wwwAndries** [KILTprotocol/mashnet-node#292]
Trying to build 1.1.0 on Ubuntu 20.04 LTS
cargo build --release -p kilt-parachain

   Compiling sc-telemetry v4.0.0-dev (https://github.com/paritytech/substrate?branch=polkadot-v0.9.11#57346f6b)
   Compiling sp-trie v4.0.0-dev (https://github.com/paritytech/substrate?branch=polkadot-v0.9.11#57346f6b)
error: Could not read `.cargo/git/checkouts/substrate-7e08433d4c370a21/57346f6/primitives/trie/Cargo.toml`.
  --> .cargo/git/checkouts/substrate-7e08433d4c370a21/57346f6/primitives/trie/src/storage_proof.rs:30:39
   |
30 | #[derive(Debug, PartialEq, Eq, Clone, Encode, Decode, TypeInfo)]
   |                                       ^^^^^^
   |
   = note: this error originates in the derive macro `Encode` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `sp-trie` due to previous error

File .cargo/git/checkouts/substrate-7e08433d4c370a21/57346f6/primitives/trie/Cargo.toml  exists and is readable.

**Comment by weichweich** [comment]
Which rust version are you using? Did you run the `scripts/init.sh` file? This should setup your rust version etc.

**Comment by wwwAndries** [comment]
stable-x86_64-unknown-linux-gnu unchanged - rustc 1.56.1 (59eed8a2a 2021-11-01)
nightly-2021-10-06-x86_64-unknown-linux-gnu unchanged - rustc 1.57.0-nightly (25ec82738 2021-10-05)

**First this warning:**
Compiling simba v0.5.1
warning: Git command failed with status: exit status: 128
warning: Could not find `.git/HEAD` searching from `/home/kilt/mashnet-node/nodes/parachain` upwards!
Compiling thread_local v1.1.3

**Later:**
Compiling sc-rpc-server v4.0.0-dev (https://github.com/paritytech/substrate?branch=polkadot-v0.9.11#57346f6b)
Compiling sp-core v4.0.0-dev (https://github.com/paritytech/substrate?branch=polkadot-v0.9.11#57346f6b)
error: Could not read `.cargo/git/checkouts/substrate-7e08433d4c370a21/57346f6/primitives/core/Cargo.toml`.
   --> .cargo/git/checkouts/substrate-7e08433d4c370a21/57346f6/primitives/core/src/crypto.rs:108:59
    |
108 | #[derive(Copy, Clone, Eq, PartialEq, Hash, Debug, Encode, Decode)]
    |                                                           ^^^^^^
    |
    = note: this error originates in the derive macro `Decode` (in Nightly builds, run with -Z macro-backtrace for more info)

Compiling memory-db v0.27.0
error: could not compile `sp-core` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by weichweich** [comment]
The warning can be ignored.
I can't reproduce the error on my machine and I don't think it's an issue with our code. Can you compile substrate itself or does this also produce errors?

**Comment by wwwAndries** [comment]
I will setup a virtual box and try again. If it doesn't succeed, I let you know. Thanks.
