### ISSUE TITLE
Setup the official testnet

### ISSUE THREAD

**Issue by tjwelde** [KILTprotocol/mashnet-node#31]
LOW, because: We will start with our current setup, just move it to kilt.io and add https. If we change something on the chain, we will redeploy and remove everything for now.

We should have a separate Testnet to our current devnet, to be able to implement things, without breaking the public net.
This includes
- chain
- services
- client

They should persist on restart and upgrade

**Comment by csmarc** [comment]
Can we close this?

**Comment by tjwelde** [comment]
We now have the mashnet and a devnet running
