### ISSUE TITLE
Use release builds in docker images

### ISSUE THREAD

**Issue by tjwelde** [KILTprotocol/mashnet-node#62]
Right now, we are using the debug build in our docker containers. Lets move over to the release build

**Comment by LeonFLK** [comment]
cargo build --release would result in the release build, thats the only difference when executing that I found for building in release mode.

**Comment by LeonFLK** [comment]
Branch `releasemodebuilding`

**Comment by tjwelde** [comment]
fixed in https://github.com/KILTprotocol/mashnet-node/pull/63
