### ISSUE TITLE
Carefully deploy latest chain code to our testnet

### ISSUE THREAD

**Issue by tjwelde** [KILTprotocol/mashnet-node#64]
This means deploying only some nodes at a time, so that they can re-sync themselves

**Comment by LeonFLK** [comment]
- started building 0.17.0

**Comment by LeonFLK** [comment]
to review check:
- [demo-client](demo.kilt.io)
- [polkadot telemetry](http://telemetry.kilt.io/#/KILT%20Testnet)

**Comment by tjwelde** [comment]
done! Good work!
