### ISSUE TITLE
Polkascan Integration

### ISSUE THREAD

**Issue by emielvanderhoek** [KILTprotocol/mashnet-node#77]
Hey,
Let me know when you are ready for integration of one of your public testnets on Polkascan.

https://polkascan.io/

**Comment by flechtnergalani** [comment]
Hi @emielvanderhoek, 

sorry for taking some time to get back to you on this. 
We would be ready and happy to integrate the KILT mashnet with Polkscan.
If you could walk me through the process and the steps we'd have to take, I'm happy to help!
